
# Adaptive Math Tutor - Theme

[theme]
primaryColor = "#209B83"
font = "sans serif"

[theme.light]
backgroundColor = "#F4FAF8"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#264B4A"

[theme.dark]
backgroundColor = "#0B1220"
secondaryBackgroundColor = "#192838"
textColor = "#ECF4FA"
